language: python
install:
  - pip install .
  - pip install --upgrade coveralls pytest pytest-cov
script:
  - coverage run setup.py pytest
jobs:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9
    - python: 3.10-dev
    - python: nightly
  allow_failures:
    - python: 3.10-dev
    - python: nightly
  fast_finish: true
after_success:
  - coveralls
