language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install .
  - pip install coveralls
script:
  - coverage run setup.py pytest
deploy:
    provider: pypi
    user: shlib
    on:
        tags: true
after_success:
  - coveralls


