#!/bin/csh -f

set nonomatch

# the rest is common to all python directories
rm -f *.pyc *.pyo .test*.sum expected result install.out
rm -rf build *.egg-info dist __pycache__ .coverage .coverage-html .eggs htmlcov
rm -rf .pytest_cache
rm -f tests/{helloworld,test,ref}
rm -f TEST REF helloworld
rm -rf tests/.pytest_cache */__pycache__ .tox
foreach i (*/clean)
    if ($i == "*/clean") break
    #echo $i
    (cd $i:h; ./clean)
end
