#!/bin/bash
# Install into ~/.local for the versions of python listed in 'pythons' below.
#
# If instead you want to install into /usr/lib or into a virtual environment, 
# use:
#     pip3 install shlib
#
# Requires Python 3.4 or better.

cmd=shlib
pythons=(python3)
    # Add the versions of python you would like to install to above

# clean out the existing installed versions
rm -rf ~/.local/lib/python*/site-packages/$cmd*

for python in ${pythons[*]}; do
    # Determine the version of python we are using
    vers=$($python -c 'import sys; print("%s.%s" % (sys.version_info[0], sys.version_info[1]))')
    echo "Installing $cmd to ~/.local (Python$vers)."

    # remove build directories from a previous install to assure a clean install
    rm -rf build dist $cmd.egg-info install.out

    # install $cmd
    $python setup.py install --quiet --user >& install.out
    if [[ $? -ne 0 ]] ; then
        echo "Problems found, aborting (see install.out)"
        exit 1
    fi
done

# remove build directories, because I like a clean directory
rm -rf build dist $cmd.egg-info
